/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package nl.woutertimmermans.connect4.protocol;


public enum C4Color implements org.apache.thrift.TEnum {
  BLACK(1),
  WHITE(2);

  private final int value;

  private C4Color(int value) {
    this.value = value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static C4Color findByValue(int value) {
    switch (value) {
      case 1:
        return BLACK;
      case 2:
        return WHITE;
      default:
        return null;
    }
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }
}
